version: "3"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - webnet
  web:
    image: jil945/fc-web:latest
    networks:
      - webnet
  
  api:
    image: jil945/fc-api:latest
    networks:
      - webnet
    
    
networks:
  webnet:
